src/Entity/Orders.php
<?php

namespace App\Entity;

use App\Repository\OrdersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrdersRepository::class)]
class Orders
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: Products::class, inversedBy: 'orders')]
    private Collection $products;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\Column]
    private ?float $total_price = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Products>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Products $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
        }

        return $this;
    }

    public function removeProduct(Products $product): static
    {
        $this->products->removeElement($product);

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->total_price;
    }

    public function setTotalPrice(float $total_price): static
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductsRepository::class)]
class Products
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categories $categories = null;

    #[ORM\ManyToMany(targetEntity: Orders::class, mappedBy: 'products')]
    private Collection $orders;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    private ?string $short_description = null;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCategories(): ?Categories
    {
        return $this->categories;
    }

    public function setCategories(?Categories $categories): static
    {
        $this->categories = $categories;

        return $this;
    }

    /**
     * @return Collection<int, Orders>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->addProduct($this);
        }

        return $this;
    }

    public function removeOrder(Orders $order): static
    {
        if ($this->orders->removeElement($order)) {
            $order->removeProduct($this);
        }

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(string $short_description): static
    {
        $this->short_description = $short_description;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 5)]
    private ?string $zipcode = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Orders::class)]
    private Collection $products;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Orders::class, orphanRemoval: true)]
    private Collection $orders;

    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): static
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Orders>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Orders $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setUser($this);
        }

        return $this;
    }

    public function removeProduct(Orders $product): static
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getUser() === $this) {
                $product->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Orders>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Orders $order): static
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }
}

templates/app/account.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon compte{% endblock %}

{% block body %}
<div class="table section-p1">
    <div class="wrapper">
        <h1>Mes Commandes</h1>        
        {% if app.user.orders %}
                {% for order in app.user.orders %}
                <table>
                    <thead>
                        <tr>
                            <th>Date d'enregistrement</th>
                            <th>Produits</th>
                            <th>Photo</th>
                            <th>Quantité</th>
                            <th>Prix total</th>
                            <th>Statue de la commande</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ order.createdAt|date("d/m/Y à H:i:s")}}</td>
                            <td>
                                <div class="order-flex order-name">
                                {% for product in order.products %}
                                    <p>{{product.name}}</p>
                                {% endfor %}
                                </div>
                            </td>
                            <td>
                                <div class="order-flex">
                                {% for product in order.products %}
                                <img class="img-fluid product-image" src="{{ asset('uploads/images/' ~ product.picture) }}" alt="">
                                {% endfor %}
                                </div>
                            </td>
                            <td>{{ order.quantity}}</td>
                            <td>{{ order.totalPrice|number_format(2, '.') }}€</td>
                            <td>{{ order.status }}</td>
                        </tr>
                    </tbody>
                </table>
                {% endfor %}
            {% else %}
            <p class="no-order">Pas encore passé de commande</p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/app/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}

{# HERO SECTION START #}

<section id="hero" class="hero">
    <div class="img-overlay img-overlay-blur">
        <div class="img-title">Bienvenue sur GameZone</div>
        <p class="img-description">Et entrer dans le monde du Jeux Vidéo</p>
        <a href="{{path('app_categories')}}" class="img-link">Voir nos produits</a>
    </div>
</section>

{# HERO SECTION END #}

<section class="product section-p1">
    <h2>Derniers jeux Playstation</h2>
    <div class="pro-container">
        {% for product in playstation %}
            <div class="pro">
                <img src="{{ asset('uploads/images/' ~ product.picture) }}" alt="">
                <div class="body">                       
                    <h3 >{{ product.name }}</h3>
                    {# <p class="des">{{ product.shortDescription }}</p> #}
                     
                </div>
                <div class="foot">
                    <p class="price">{{ product.price }}€</p>
                     <a href="{{ path('show_products', {id: product.id}) }}" ><i class="fa-solid fa-magnifying-glass"></i></a>
                </div>
            </div>
        {% endfor %}
    </div>
</section>

<section class="product section-p1">
    <h2>Derniers jeux Xbox</h2>
    <div class="pro-container">
        {% for product in xbox %}
            <div class="pro">
                <img src="{{ asset('uploads/images/' ~ product.picture) }}" alt="">
                <div class="body">                       
                    <h3 >{{ product.name }}</h3>
                    {# <p class="des">{{ product.shortDescription }}</p> #}
                     
                </div>
                <div class="foot">
                    <p class="price">{{ product.price }}€</p>
                     <a href="{{ path('show_products', {id: product.id}) }}" ><i class="fa-solid fa-magnifying-glass"></i></a>
                </div>
            </div>
        {% endfor %}
    </div>
</section>

<section class="product section-p1">
    <h2>Derniers jeux Nintendo</h2>
    <div class="pro-container">
        {% for product in nintendo %}
            <div class="pro">
                <img src="{{ asset('uploads/images/' ~ product.picture) }}" alt="">
                <div class="body">                       
                    <h3 >{{ product.name }}</h3>
                    {# <p class="des">{{ product.shortDescription }}</p> #}
                     
                </div>
                <div class="foot">
                    <p class="price">{{ product.price }}€</p>
                     <a href="{{ path('show_products', {id: product.id}) }}" ><i class="fa-solid fa-magnifying-glass"></i></a>
                </div>
            </div>
        {% endfor %}
    </div>
</section>

<section class="product section-p1">
    <h2>Derniers jeux PC</h2>
    <div class="pro-container">
        {% for product in pc %}
            <div class="pro">
                <img src="{{ asset('uploads/images/' ~ product.picture) }}" alt="">
                <div class="body">                       
                    <h3 >{{ product.name }}</h3>
                    {# <p class="des">{{ product.shortDescription }}</p> #}
                     
                </div>
                <div class="foot">
                    <p class="price">{{ product.price }}€</p>
                    <a href="{{ path('show_products', {id: product.id}) }}" ><i class="fa-solid fa-magnifying-glass"></i></a>
                </div>
            </div>
        {% endfor %}
    </div>
</section>

<section class="news section-p1">
    <h2>Les dernières actualités  et promotions Gaming</h2>
    <div class="news-container">
        {% for article in articles %}
                <div class="new">
                    <img src="{{ article.urlToImage }}" alt="Image non disponible">
                    <div class="body">
                        <h3 class="news-title">{{ article.title }}</h3>
                        <p>{{ article.description }}</p>
                        <p>Auteur:
                            {% if article.author %}
                                {{ article.author }}
                            {% else %}
                                Auteur inconnu
                            {% endif %}
                        </p>
                        <p>Date de publication:{{ article.publishedAt }}</p>
                        
                    </div>
                    <a href="{{ article.url }}">Lire l'article entier</a>
                </div>
        {% endfor %}
    </div>
</section>

<section class="product section-p1">
    <h2>Dernieres Consoles</h2>
    <div class="pro-container">
        {% for product in consoles %}
            <div class="pro">
                <img src="{{ asset('uploads/images/' ~ product.picture) }}" alt="">
                <div class="body">                       
                    <h3 >{{ product.name }}</h3>
                    {# <p class="des">{{ product.shortDescription }}</p> #}
                     
                </div>
                <div class="foot">
                    <p class="price">{{ product.price }}€</p>
                    <a href="{{ path('show_products', {id: product.id}) }}" ><i class="fa-solid fa-magnifying-glass"></i></a>
                </div>
            </div>
        {% endfor %}
    </div>
</section>

<section class="product section-p1">
    <h2>Dernieres Manettes</h2>
    <div class="pro-container">
        {% for product in manettes %}
            <div class="pro">
                <img src="{{ asset('uploads/images/' ~ product.picture) }}" alt="">
                <div class="body">                       
                    <h3 >{{ product.name }}</h3>
                    {# <p class="des">{{ product.shortDescription }}</p> #}
                     
                </div>
                <div class="foot">
                    <p class="price">{{ product.price }}€</p>
                    <a href="{{ path('show_products', {id: product.id}) }}" ><i class="fa-solid fa-magnifying-glass"></i></a>
                </div>
            </div>
        {% endfor %}
    </div>
</section>

<section class="product section-p1">
    <h2>Derniers clavier/souris</h2>
    <div class="pro-container">
        {% for product in materielpc %}
            <div class="pro">
                <img src="{{ asset('uploads/images/' ~ product.picture) }}" alt="">
                <div class="body">                       
                    <h3 >{{ product.name }}</h3>
                    {# <p class="des">{{ product.shortDescription }}</p> #}
                </div>
                <div class="foot">
                    <p class="price">{{ product.price }}€</p>
                    <a href="{{ path('show_products', {id: product.id}) }}" ><i class="fa-solid fa-magnifying-glass"></i></a>
                </div>
            </div>
        {% endfor %}
    </div>
</section>


{% endblock %}